[2024-09-15 17:19:15,876] INFO: main: WELCOME TO OUR CUSTOM LOG!!
[2024-09-16 13:25:20,584] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-16 13:25:20,595] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-16 13:25:20,597] INFO: common: created directory at: artifacts
[2024-09-16 13:25:20,600] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-16 13:25:20,601] INFO: 967806046: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-16 13:25:32,240] INFO: 967806046: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-16 14:23:53,942] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-16 14:23:53,944] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-16 14:23:53,947] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-16 14:23:53,947] INFO: common: created directory at: artifacts
[2024-09-16 14:23:53,948] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-16 14:23:53,948] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-16 14:24:09,109] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-16 14:24:09,735] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-16 14:31:33,934] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-16 14:31:33,935] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-16 14:31:33,937] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-16 14:31:33,937] INFO: common: created directory at: artifacts
[2024-09-16 14:31:33,938] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-16 14:31:33,938] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-16 14:31:45,318] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-16 14:31:45,874] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 16:10:11,574] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:10:11,617] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:10:11,627] INFO: common: created directory at: artifacts
[2024-09-17 16:10:11,631] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:10:47,264] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:10:47,275] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:10:47,277] INFO: common: created directory at: artifacts
[2024-09-17 16:10:47,279] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:11:57,484] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:11:57,487] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:11:57,490] INFO: common: created directory at: artifacts
[2024-09-17 16:11:57,491] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:12:07,920] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-09-17 16:13:38,982] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:13:38,986] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:13:38,988] INFO: common: created directory at: artifacts
[2024-09-17 16:13:38,989] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:13:40,058] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-09-17 16:33:31,159] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 16:33:31,161] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:33:31,164] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:33:31,164] INFO: common: created directory at: artifacts
[2024-09-17 16:33:31,165] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 16:33:31,165] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:33:47,654] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:33:48,333] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 16:33:48,333] INFO: main: ************************************************
[2024-09-17 16:33:48,334] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 16:33:48,334] ERROR: main: get_prepare_base_model_config() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
TypeError: get_prepare_base_model_config() missing 1 required positional argument: 'self'
[2024-09-17 16:36:53,883] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 16:36:53,885] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:36:53,887] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:36:53,888] INFO: common: created directory at: artifacts
[2024-09-17 16:36:53,888] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 16:36:53,888] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:37:05,839] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:37:06,374] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 16:37:06,375] INFO: main: ************************************************
[2024-09-17 16:37:06,375] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 16:37:06,375] ERROR: main: get_prepare_base_model_config() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
TypeError: get_prepare_base_model_config() missing 1 required positional argument: 'self'
[2024-09-17 16:43:19,448] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 16:43:19,450] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:43:19,451] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:43:19,452] INFO: common: created directory at: artifacts
[2024-09-17 16:43:19,452] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 16:43:19,452] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:43:33,793] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:43:34,366] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 16:43:34,366] INFO: main: ************************************************
[2024-09-17 16:43:34,366] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 16:43:34,368] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:43:34,370] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:43:34,370] INFO: common: created directory at: artifacts
[2024-09-17 16:43:34,370] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:43:34,372] ERROR: main: "'ConfigBox' object has no attribute 'updated_base_model_path'"
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 26, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\config\configuration.py", line 38, in get_prepare_base_model_config
    updated_base_model_path=Path(config.updated_base_model_path),
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'updated_base_model_path'"
[2024-09-17 16:50:59,252] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 16:50:59,262] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:50:59,267] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:50:59,268] INFO: common: created directory at: artifacts
[2024-09-17 16:50:59,268] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 16:50:59,269] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:51:10,773] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:51:11,436] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 16:51:11,436] INFO: main: ************************************************
[2024-09-17 16:51:11,436] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 16:51:11,438] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:51:11,439] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:51:11,440] INFO: common: created directory at: artifacts
[2024-09-17 16:51:11,440] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:51:11,440] ERROR: main: __init__() got an unexpected keyword argument 'updated_base_model_path'
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\config\configuration.py", line 35, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: __init__() got an unexpected keyword argument 'updated_base_model_path'
[2024-09-17 16:53:06,930] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:53:06,939] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:53:06,942] INFO: common: created directory at: artifacts
[2024-09-17 16:53:06,944] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:53:32,308] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:53:32,311] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:53:32,314] INFO: common: created directory at: artifacts
[2024-09-17 16:53:32,315] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:54:25,994] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:54:25,997] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:54:25,999] INFO: common: created directory at: artifacts
[2024-09-17 16:54:26,002] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:55:55,812] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:55:55,816] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:55:55,818] INFO: common: created directory at: artifacts
[2024-09-17 16:55:55,819] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:55:59,769] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:55:59,772] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:55:59,774] INFO: common: created directory at: artifacts
[2024-09-17 16:55:59,774] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:56:00,433] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:56:00,436] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:56:00,438] INFO: common: created directory at: artifacts
[2024-09-17 16:56:00,439] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:57:07,575] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:57:07,578] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:57:07,581] INFO: common: created directory at: artifacts
[2024-09-17 16:57:07,582] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:57:31,555] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:57:31,558] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:57:31,560] INFO: common: created directory at: artifacts
[2024-09-17 16:57:31,562] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:57:32,264] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-09-17 16:57:48,086] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 16:57:48,090] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:57:48,118] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:57:48,125] INFO: common: created directory at: artifacts
[2024-09-17 16:57:48,127] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 16:57:48,129] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:58:00,322] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 16:58:01,486] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 16:58:01,487] INFO: main: ************************************************
[2024-09-17 16:58:01,487] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 16:58:01,490] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 16:58:01,492] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 16:58:01,494] INFO: common: created directory at: artifacts
[2024-09-17 16:58:01,494] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 16:58:01,494] ERROR: main: __init__() got an unexpected keyword argument 'updated_base_model_path'
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\config\configuration.py", line 35, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: __init__() got an unexpected keyword argument 'updated_base_model_path'
[2024-09-17 17:00:29,285] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 17:00:29,326] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 17:00:29,330] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 17:00:29,331] INFO: common: created directory at: artifacts
[2024-09-17 17:00:29,331] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 17:00:29,332] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 17:00:40,935] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 17:00:41,564] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 17:00:41,564] INFO: main: ************************************************
[2024-09-17 17:00:41,564] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 17:00:41,566] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 17:00:41,568] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 17:00:41,569] INFO: common: created directory at: artifacts
[2024-09-17 17:00:41,570] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 17:00:41,570] ERROR: main: __init__() got an unexpected keyword argument 'params_weights'
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\src\cnnClassifier\config\configuration.py", line 35, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: __init__() got an unexpected keyword argument 'params_weights'
[2024-09-17 17:02:33,964] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 17:02:33,966] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 17:02:33,968] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 17:02:33,968] INFO: common: created directory at: artifacts
[2024-09-17 17:02:33,969] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 17:02:33,969] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 17:02:46,193] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 17:02:46,691] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 17:02:46,692] INFO: main: ************************************************
[2024-09-17 17:02:46,692] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 17:02:46,693] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 17:02:46,695] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 17:02:46,695] INFO: common: created directory at: artifacts
[2024-09-17 17:02:46,696] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 17:02:47,260] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-09-17 17:02:47,576] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 17:03:11,613] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-17 17:03:11,615] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 17:03:11,617] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 17:03:11,618] INFO: common: created directory at: artifacts
[2024-09-17 17:03:11,618] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-17 17:03:11,618] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 17:03:24,272] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-17 17:03:24,888] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-17 17:03:24,889] INFO: main: ************************************************
[2024-09-17 17:03:24,889] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-17 17:03:24,891] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-17 17:03:24,892] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-17 17:03:24,892] INFO: common: created directory at: artifacts
[2024-09-17 17:03:24,893] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-17 17:03:25,369] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-09-17 17:03:25,648] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-09-30 01:27:31,676] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-30 01:27:31,713] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-30 01:27:31,729] INFO: common: created directory at: artifacts
[2024-09-30 01:27:31,731] INFO: common: created directory at: artifacts\training
[2024-09-30 01:28:31,802] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-30 01:28:31,805] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-30 01:28:31,806] INFO: common: created directory at: artifacts
[2024-09-30 01:28:31,808] INFO: common: created directory at: artifacts\training
[2024-09-30 01:30:19,756] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-30 01:30:19,763] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-30 01:30:19,766] INFO: common: created directory at: artifacts
[2024-09-30 01:30:19,768] INFO: common: created directory at: artifacts\training
[2024-09-30 01:42:55,052] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-09-30 01:42:55,055] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-30 01:42:55,057] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-30 01:42:55,058] INFO: common: created directory at: artifacts
[2024-09-30 01:42:55,058] INFO: common: created directory at: artifacts/data_ingestion
[2024-09-30 01:42:55,058] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-30 01:43:27,002] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-09-30 01:43:27,824] INFO: main: >>>>>>>>>> STAGE DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-09-30 01:43:27,824] INFO: main: ************************************************
[2024-09-30 01:43:27,824] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-09-30 01:43:27,826] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-30 01:43:27,829] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-30 01:43:27,829] INFO: common: created directory at: artifacts
[2024-09-30 01:43:27,830] INFO: common: created directory at: artifacts/prepare_base_model
[2024-09-30 01:43:28,589] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-09-30 01:43:28,971] INFO: main: >>>>>>>>>> STAGE PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-09-30 01:43:28,971] INFO: main: ************************************************
[2024-09-30 01:43:28,972] INFO: main: >>>>>>>>>> STAGE TRAINING STARTED <<<<<<<<<<
[2024-09-30 01:43:28,974] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-09-30 01:43:28,976] INFO: common: yaml file: params.yaml loaded successfully
[2024-09-30 01:43:28,977] INFO: common: created directory at: artifacts
[2024-09-30 01:43:28,977] INFO: common: created directory at: artifacts\training
[2024-09-30 01:44:16,565] INFO: main: >>>>>>>>>> STAGE TRAINING COMPLETED <<<<<<<<<<

x=========================x
[2024-10-01 23:14:47,096] INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/Kabeeraa27/Kidney-Disease-Classification-MLflow-DVC "HTTP/1.1 200 OK"
[2024-10-01 23:14:47,154] INFO: helpers: Initialized MLflow to track repo "Kabeeraa27/Kidney-Disease-Classification-MLflow-DVC"
[2024-10-01 23:14:47,162] INFO: helpers: Repository Kabeeraa27/Kidney-Disease-Classification-MLflow-DVC initialized!
[2024-10-01 23:26:15,165] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-01 23:26:15,209] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-01 23:26:15,216] INFO: common: created directory at: artifacts
[2024-10-01 23:28:54,745] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-01 23:28:54,760] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-01 23:28:54,769] INFO: common: created directory at: artifacts
[2024-10-01 23:30:08,300] INFO: common: json file saved at: scores.json
[2024-10-01 23:30:13,222] WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-10-01 23:30:15,094] INFO: builder_impl: Assets written to: C:\Users\kabee\AppData\Local\Temp\tmpv0inzadg\model\data\model\assets
[2024-10-01 23:34:08,712] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-01 23:34:08,753] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-01 23:34:08,772] INFO: common: created directory at: artifacts
[2024-10-01 23:35:13,346] INFO: common: json file saved at: scores.json
[2024-10-01 23:35:18,536] WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-10-01 23:35:19,978] INFO: builder_impl: Assets written to: C:\Users\kabee\AppData\Local\Temp\tmpfmjq5f6p\model\data\model\assets
[2024-10-01 23:47:46,045] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-01 23:47:46,088] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-01 23:47:46,091] INFO: common: created directory at: artifacts
[2024-10-01 23:48:26,519] INFO: common: json file saved at: scores.json
[2024-10-01 23:48:30,128] WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-10-01 23:48:31,104] INFO: builder_impl: Assets written to: C:\Users\kabee\AppData\Local\Temp\tmp7d8sl8l_\model\data\model\assets
[2024-10-01 23:48:52,465] WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /Kabeeraa27/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow/runs/get?run_uuid=76d2f2a5dfcf4ee3bf5110d09f067c6a&run_id=76d2f2a5dfcf4ee3bf5110d09f067c6a
[2024-10-01 23:48:59,192] WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /Kabeeraa27/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow-artifacts/artifacts/1840554e68444f28ab5c930b2b99d783/76d2f2a5dfcf4ee3bf5110d09f067c6a/artifacts/model/data/model/keras_metadata.pb
[2024-10-01 23:55:37,636] WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /Kabeeraa27/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow-artifacts/artifacts/1840554e68444f28ab5c930b2b99d783/76d2f2a5dfcf4ee3bf5110d09f067c6a/artifacts/model/data/model/variables/variables.data-00000-of-00001
[2024-10-01 23:56:10,392] WARNING: connectionpool: Retrying (Retry(total=3, connect=5, read=3, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /Kabeeraa27/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow-artifacts/artifacts/1840554e68444f28ab5c930b2b99d783/76d2f2a5dfcf4ee3bf5110d09f067c6a/artifacts/model/data/model/variables/variables.data-00000-of-00001
[2024-10-01 23:57:14,821] WARNING: connectionpool: Retrying (Retry(total=2, connect=5, read=2, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /Kabeeraa27/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow-artifacts/artifacts/1840554e68444f28ab5c930b2b99d783/76d2f2a5dfcf4ee3bf5110d09f067c6a/artifacts/model/data/model/variables/variables.data-00000-of-00001
[2024-10-01 23:58:06,328] WARNING: connectionpool: Retrying (Retry(total=1, connect=5, read=1, redirect=5, status=5)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /Kabeeraa27/Kidney-Disease-Classification-MLflow-DVC.mlflow/api/2.0/mlflow-artifacts/artifacts/1840554e68444f28ab5c930b2b99d783/76d2f2a5dfcf4ee3bf5110d09f067c6a/artifacts/model/data/model/variables/variables.data-00000-of-00001
[2024-10-02 00:01:49,844] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:01:49,880] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:01:49,884] INFO: common: created directory at: artifacts
[2024-10-02 00:02:27,711] INFO: common: json file saved at: scores.json
[2024-10-02 00:02:30,897] WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-10-02 00:02:31,703] INFO: builder_impl: Assets written to: C:\Users\kabee\AppData\Local\Temp\tmpx28nzcco\model\data\model\assets
[2024-10-02 00:30:20,348] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:30:20,355] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:30:20,359] INFO: common: created directory at: artifacts
[2024-10-02 00:30:53,754] INFO: common: json file saved at: scores.json
[2024-10-02 00:30:53,758] INFO: common: json file saved at: scores.json
[2024-10-02 00:30:56,597] WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-10-02 00:30:57,278] INFO: builder_impl: Assets written to: C:\Users\kabee\AppData\Local\Temp\tmp1_nhnfm5\model\data\model\assets
[2024-10-02 00:36:26,895] INFO: main: >>>>>>>>>> DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-10-02 00:36:26,899] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:36:26,902] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:36:26,903] INFO: common: created directory at: artifacts
[2024-10-02 00:36:26,903] INFO: common: created directory at: artifacts/data_ingestion
[2024-10-02 00:36:26,904] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 00:36:42,903] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 00:36:44,379] INFO: main: >>>>>>>>>> DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 00:36:44,380] INFO: main: ************************************************
[2024-10-02 00:36:44,381] INFO: main: >>>>>>>>>> PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-10-02 00:36:44,384] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:36:44,386] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:36:44,387] INFO: common: created directory at: artifacts
[2024-10-02 00:36:44,388] INFO: common: created directory at: artifacts/prepare_base_model
[2024-10-02 00:36:46,146] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-10-02 00:36:47,118] INFO: main: >>>>>>>>>> PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 00:36:47,120] INFO: main: ************************************************
[2024-10-02 00:36:47,120] INFO: main: >>>>>>>>>> TRAINING STARTED <<<<<<<<<<
[2024-10-02 00:36:47,125] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:36:47,132] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:36:47,136] INFO: common: created directory at: artifacts
[2024-10-02 00:36:47,138] INFO: common: created directory at: artifacts\training
[2024-10-02 00:38:15,948] INFO: main: >>>>>>>>>> TRAINING COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 00:38:15,951] INFO: main: ************************************************
[2024-10-02 00:38:15,951] INFO: main: >>>>>>>>>> EVALUATION STARTED <<<<<<<<<<
[2024-10-02 00:38:15,961] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:38:15,967] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:38:15,970] INFO: common: created directory at: artifacts
[2024-10-02 00:38:16,529] ERROR: main: name 'model' is not defined
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 16, in main
    evaluation.evaluation()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_evaluation_mlflow.py", line 47, in evaluation
    self.score = model.evaluate(self.valid_generator)
NameError: name 'model' is not defined
[2024-10-02 00:40:20,301] INFO: main: >>>>>>>>>> DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-10-02 00:40:20,304] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:40:20,308] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:40:20,308] INFO: common: created directory at: artifacts
[2024-10-02 00:40:20,309] INFO: common: created directory at: artifacts/data_ingestion
[2024-10-02 00:40:20,309] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 00:40:35,733] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 00:40:38,201] INFO: main: >>>>>>>>>> DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 00:40:38,203] INFO: main: ************************************************
[2024-10-02 00:40:38,203] INFO: main: >>>>>>>>>> PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-10-02 00:40:38,212] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:40:38,218] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:40:38,222] INFO: common: created directory at: artifacts
[2024-10-02 00:40:38,224] INFO: common: created directory at: artifacts/prepare_base_model
[2024-10-02 00:40:39,874] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-10-02 00:40:41,157] INFO: main: >>>>>>>>>> PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 00:40:41,158] INFO: main: ************************************************
[2024-10-02 00:40:41,158] INFO: main: >>>>>>>>>> TRAINING STARTED <<<<<<<<<<
[2024-10-02 00:40:41,161] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:40:41,162] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:40:41,163] INFO: common: created directory at: artifacts
[2024-10-02 00:40:41,163] INFO: common: created directory at: artifacts\training
[2024-10-02 00:42:03,991] INFO: main: >>>>>>>>>> TRAINING COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 00:42:03,994] INFO: main: ************************************************
[2024-10-02 00:42:03,994] INFO: main: >>>>>>>>>> EVALUATION STARTED <<<<<<<<<<
[2024-10-02 00:42:04,001] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:42:04,007] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:42:04,011] INFO: common: created directory at: artifacts
[2024-10-02 00:42:30,531] INFO: common: json file saved at: scores.json
[2024-10-02 00:42:30,533] INFO: common: json file saved at: scores.json
[2024-10-02 00:42:30,534] INFO: main: >>>>>>>>>> EVALUATION COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 00:49:25,274] INFO: main: >>>>>>>>>> DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-10-02 00:49:25,278] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:49:25,282] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:49:25,283] INFO: common: created directory at: artifacts
[2024-10-02 00:49:25,284] INFO: common: created directory at: artifacts/data_ingestion
[2024-10-02 00:49:25,284] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 00:49:37,986] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 00:49:38,809] INFO: main: >>>>>>>>>> DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 00:49:38,810] INFO: main: ************************************************
[2024-10-02 00:49:38,810] INFO: main: >>>>>>>>>> PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-10-02 00:49:38,812] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:49:38,813] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:49:38,814] INFO: common: created directory at: artifacts
[2024-10-02 00:49:38,815] INFO: common: created directory at: artifacts/prepare_base_model
[2024-10-02 00:49:39,527] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-10-02 00:49:40,104] INFO: main: >>>>>>>>>> PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 00:49:40,105] INFO: main: ************************************************
[2024-10-02 00:49:40,105] INFO: main: >>>>>>>>>> TRAINING STARTED <<<<<<<<<<
[2024-10-02 00:49:40,109] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:49:40,112] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:49:40,114] INFO: common: created directory at: artifacts
[2024-10-02 00:49:40,116] INFO: common: created directory at: artifacts\training
[2024-10-02 00:51:07,751] INFO: main: >>>>>>>>>> TRAINING COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 00:51:07,754] INFO: main: ************************************************
[2024-10-02 00:51:07,754] INFO: main: >>>>>>>>>> EVALUATION STARTED <<<<<<<<<<
[2024-10-02 00:51:07,760] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 00:51:07,766] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 00:51:07,769] INFO: common: created directory at: artifacts
[2024-10-02 00:51:34,080] INFO: common: json file saved at: scores.json
[2024-10-02 00:51:34,085] INFO: common: json file saved at: scores.json
[2024-10-02 00:51:34,086] INFO: main: >>>>>>>>>> EVALUATION COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:05:51,103] INFO: main: >>>>>>>>>> DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-10-02 01:05:51,110] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:05:51,117] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:05:51,120] INFO: common: created directory at: artifacts
[2024-10-02 01:05:51,121] INFO: common: created directory at: artifacts/data_ingestion
[2024-10-02 01:05:51,122] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 01:05:58,665] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 01:05:59,543] INFO: main: >>>>>>>>>> DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:05:59,543] INFO: main: ************************************************
[2024-10-02 01:05:59,543] INFO: main: >>>>>>>>>> PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-10-02 01:05:59,545] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:05:59,547] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:05:59,547] INFO: common: created directory at: artifacts
[2024-10-02 01:05:59,549] INFO: common: created directory at: artifacts/prepare_base_model
[2024-10-02 01:06:00,475] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-10-02 01:06:00,983] INFO: main: >>>>>>>>>> PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:06:00,986] INFO: main: ************************************************
[2024-10-02 01:06:00,986] INFO: main: >>>>>>>>>> TRAINING STARTED <<<<<<<<<<
[2024-10-02 01:06:00,988] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:06:00,989] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:06:00,990] INFO: common: created directory at: artifacts
[2024-10-02 01:06:00,991] INFO: common: created directory at: artifacts\training
[2024-10-02 01:07:22,840] INFO: main: >>>>>>>>>> TRAINING COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:07:22,842] INFO: main: ************************************************
[2024-10-02 01:07:22,842] INFO: main: >>>>>>>>>> EVALUATION STARTED <<<<<<<<<<
[2024-10-02 01:07:22,845] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:07:22,850] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:07:22,851] INFO: common: created directory at: artifacts
[2024-10-02 01:07:55,732] INFO: common: json file saved at: scores.json
[2024-10-02 01:07:55,748] INFO: common: json file saved at: scores.json
[2024-10-02 01:07:55,752] INFO: main: >>>>>>>>>> EVALUATION COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:11:40,323] INFO: main: >>>>>>>>>> DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-10-02 01:11:40,327] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:11:40,331] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:11:40,332] INFO: common: created directory at: artifacts
[2024-10-02 01:11:40,333] INFO: common: created directory at: artifacts/data_ingestion
[2024-10-02 01:11:40,336] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 01:11:47,759] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 01:11:48,643] INFO: main: >>>>>>>>>> DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:11:48,643] INFO: main: ************************************************
[2024-10-02 01:11:48,643] INFO: main: >>>>>>>>>> PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-10-02 01:11:48,645] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:11:48,646] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:11:48,647] INFO: common: created directory at: artifacts
[2024-10-02 01:11:48,647] INFO: common: created directory at: artifacts/prepare_base_model
[2024-10-02 01:11:49,325] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-10-02 01:11:50,078] INFO: main: >>>>>>>>>> PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:11:50,080] INFO: main: ************************************************
[2024-10-02 01:11:50,080] INFO: main: >>>>>>>>>> TRAINING STARTED <<<<<<<<<<
[2024-10-02 01:11:50,083] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:11:50,085] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:11:50,086] INFO: common: created directory at: artifacts
[2024-10-02 01:11:50,087] INFO: common: created directory at: artifacts\training
[2024-10-02 01:13:24,974] INFO: main: >>>>>>>>>> TRAINING COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:13:24,977] INFO: main: ************************************************
[2024-10-02 01:13:24,977] INFO: main: >>>>>>>>>> EVALUATION STARTED <<<<<<<<<<
[2024-10-02 01:13:24,984] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:13:24,989] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:13:24,992] INFO: common: created directory at: artifacts
[2024-10-02 01:13:52,446] INFO: common: json file saved at: scores.json
[2024-10-02 01:13:52,450] INFO: common: json file saved at: scores.json
[2024-10-02 01:13:55,577] WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-10-02 01:13:56,378] INFO: builder_impl: Assets written to: C:\Users\kabee\AppData\Local\Temp\tmpr7w2t6qv\model\data\model\assets
[2024-10-02 01:14:11,209] INFO: dir_util: creating C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\23ac1b61d560435e810b902670a38961\artifacts\model\data
[2024-10-02 01:14:11,213] INFO: dir_util: creating C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\23ac1b61d560435e810b902670a38961\artifacts\model\data\model
[2024-10-02 01:14:11,214] INFO: dir_util: creating C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\23ac1b61d560435e810b902670a38961\artifacts\model\data\model\assets
[2024-10-02 01:14:11,220] INFO: dir_util: creating C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\23ac1b61d560435e810b902670a38961\artifacts\model\data\model\variables
[2024-10-02 01:14:11,388] INFO: main: >>>>>>>>>> EVALUATION COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:22:47,629] INFO: main: >>>>>>>>>> DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-10-02 01:22:47,633] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:22:47,636] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:22:47,637] INFO: common: created directory at: artifacts
[2024-10-02 01:22:47,638] INFO: common: created directory at: artifacts/data_ingestion
[2024-10-02 01:22:47,639] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 01:22:55,192] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 01:22:56,054] INFO: main: >>>>>>>>>> DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:22:56,055] INFO: main: ************************************************
[2024-10-02 01:22:56,055] INFO: main: >>>>>>>>>> PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-10-02 01:22:56,057] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:22:56,058] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:22:56,059] INFO: common: created directory at: artifacts
[2024-10-02 01:22:56,060] INFO: common: created directory at: artifacts/prepare_base_model
[2024-10-02 01:22:56,951] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-10-02 01:22:58,271] INFO: main: >>>>>>>>>> PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:22:58,272] INFO: main: ************************************************
[2024-10-02 01:22:58,272] INFO: main: >>>>>>>>>> TRAINING STARTED <<<<<<<<<<
[2024-10-02 01:22:58,274] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:22:58,276] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:22:58,276] INFO: common: created directory at: artifacts
[2024-10-02 01:22:58,277] INFO: common: created directory at: artifacts\training
[2024-10-02 01:24:45,143] INFO: main: >>>>>>>>>> TRAINING COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:24:45,148] INFO: main: ************************************************
[2024-10-02 01:24:45,148] INFO: main: >>>>>>>>>> EVALUATION STARTED <<<<<<<<<<
[2024-10-02 01:24:45,158] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:24:45,163] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:24:45,167] INFO: common: created directory at: artifacts
[2024-10-02 01:25:06,662] INFO: common: json file saved at: scores.json
[2024-10-02 01:25:06,663] INFO: common: json file saved at: scores.json
[2024-10-02 01:25:09,702] WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-10-02 01:25:10,465] INFO: builder_impl: Assets written to: C:\Users\kabee\AppData\Local\Temp\tmp2ku38hcz\model\data\model\assets
[2024-10-02 01:25:27,395] INFO: dir_util: creating C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\54222397f00744e788c6d0dca87c06d0\artifacts\model\data
[2024-10-02 01:25:27,399] INFO: dir_util: creating C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\54222397f00744e788c6d0dca87c06d0\artifacts\model\data\model
[2024-10-02 01:25:27,400] INFO: dir_util: creating C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\54222397f00744e788c6d0dca87c06d0\artifacts\model\data\model\assets
[2024-10-02 01:25:27,410] INFO: dir_util: creating C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\54222397f00744e788c6d0dca87c06d0\artifacts\model\data\model\variables
[2024-10-02 01:25:27,680] INFO: main: >>>>>>>>>> EVALUATION COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:39:35,910] INFO: main: >>>>>>>>>> DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-10-02 01:39:35,912] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:39:35,916] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:39:35,917] INFO: common: created directory at: artifacts
[2024-10-02 01:39:35,918] INFO: common: created directory at: artifacts/data_ingestion
[2024-10-02 01:39:35,918] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 01:39:44,170] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-02 01:39:44,837] INFO: main: >>>>>>>>>> DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:39:44,838] INFO: main: ************************************************
[2024-10-02 01:39:44,838] INFO: main: >>>>>>>>>> PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-10-02 01:39:44,840] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:39:44,842] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:39:44,842] INFO: common: created directory at: artifacts
[2024-10-02 01:39:44,843] INFO: common: created directory at: artifacts/prepare_base_model
[2024-10-02 01:39:45,547] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-10-02 01:39:45,967] INFO: main: >>>>>>>>>> PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:39:45,968] INFO: main: ************************************************
[2024-10-02 01:39:45,968] INFO: main: >>>>>>>>>> TRAINING STARTED <<<<<<<<<<
[2024-10-02 01:39:45,970] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:39:45,971] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:39:45,973] INFO: common: created directory at: artifacts
[2024-10-02 01:39:45,974] INFO: common: created directory at: artifacts\training
[2024-10-02 01:40:52,905] INFO: main: >>>>>>>>>> TRAINING COMPLETED <<<<<<<<<<

x=========================x
[2024-10-02 01:40:52,908] INFO: main: ************************************************
[2024-10-02 01:40:52,908] INFO: main: >>>>>>>>>> EVALUATION STARTED <<<<<<<<<<
[2024-10-02 01:40:52,915] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-02 01:40:52,920] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-02 01:40:52,925] INFO: common: created directory at: artifacts
[2024-10-02 01:41:13,933] INFO: common: json file saved at: scores.json
[2024-10-02 01:41:13,935] INFO: common: json file saved at: scores.json
[2024-10-02 01:41:16,314] WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2024-10-02 01:41:16,914] INFO: builder_impl: Assets written to: C:\Users\kabee\AppData\Local\Temp\tmprnvdtqmx\model\data\model\assets
[2024-10-02 01:41:30,970] INFO: dir_util: creating C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\1ff023ada8b9471aa57042019ef5c26f\artifacts\model\data
[2024-10-02 01:41:30,974] INFO: dir_util: creating C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\1ff023ada8b9471aa57042019ef5c26f\artifacts\model\data\model
[2024-10-02 01:41:30,975] INFO: dir_util: creating C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\1ff023ada8b9471aa57042019ef5c26f\artifacts\model\data\model\assets
[2024-10-02 01:41:30,980] INFO: dir_util: creating C:\Users\kabee\OneDrive\Desktop\DS PROJ3\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\1ff023ada8b9471aa57042019ef5c26f\artifacts\model\data\model\variables
[2024-10-02 01:41:31,139] INFO: main: >>>>>>>>>> EVALUATION COMPLETED <<<<<<<<<<

x=========================x
[2024-10-07 15:50:59,593] INFO: main: >>>>>>>>>> DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-10-07 15:50:59,598] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-07 15:50:59,602] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-07 15:50:59,604] INFO: common: created directory at: artifacts
[2024-10-07 15:50:59,605] INFO: common: created directory at: artifacts/data_ingestion
[2024-10-07 15:50:59,605] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-07 15:52:19,730] ERROR: main: ("Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Traceback (most recent call last):
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 444, in _error_catcher
    yield
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\http\client.py", line 459, in read
    n = self.readinto(b)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\http\client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 593, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    obj.main()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\data_ingestion.py", line 32, in download_file
    raise e
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\data_ingestion.py", line 27, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\gdown\download.py", line 368, in download
    for chunk in res.iter_content(chunk_size=CHUNK_SIZE):
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
[2024-10-07 15:52:44,268] INFO: main: >>>>>>>>>> DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-10-07 15:52:44,272] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-07 15:52:44,274] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-07 15:52:44,274] INFO: common: created directory at: artifacts
[2024-10-07 15:52:44,275] INFO: common: created directory at: artifacts/data_ingestion
[2024-10-07 15:52:44,275] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-07 15:53:58,786] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-07 15:53:59,738] INFO: main: >>>>>>>>>> DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-10-07 15:53:59,738] INFO: main: ************************************************
[2024-10-07 15:53:59,739] INFO: main: >>>>>>>>>> PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-10-07 15:53:59,742] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-07 15:53:59,744] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-07 15:53:59,745] INFO: common: created directory at: artifacts
[2024-10-07 15:53:59,746] INFO: common: created directory at: artifacts/prepare_base_model
[2024-10-07 15:54:00,684] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-10-07 15:54:01,062] INFO: main: >>>>>>>>>> PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-10-07 15:54:01,063] INFO: main: ************************************************
[2024-10-07 15:54:01,063] INFO: main: >>>>>>>>>> TRAINING STARTED <<<<<<<<<<
[2024-10-07 15:54:01,065] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-07 15:54:01,068] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-07 15:54:01,068] INFO: common: created directory at: artifacts
[2024-10-07 15:54:01,069] INFO: common: created directory at: artifacts\training
[2024-10-07 15:54:58,204] INFO: main: >>>>>>>>>> TRAINING COMPLETED <<<<<<<<<<

x=========================x
[2024-10-07 15:54:58,207] INFO: main: ************************************************
[2024-10-07 15:54:58,207] INFO: main: >>>>>>>>>> EVALUATION STARTED <<<<<<<<<<
[2024-10-07 15:54:58,210] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-07 15:54:58,219] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-07 15:54:58,222] INFO: common: created directory at: artifacts
[2024-10-07 15:55:14,408] INFO: common: json file saved at: scores.json
[2024-10-07 15:55:14,409] INFO: common: json file saved at: scores.json
[2024-10-07 15:55:14,409] INFO: main: >>>>>>>>>> EVALUATION COMPLETED <<<<<<<<<<

x=========================x
[2024-10-07 16:03:22,399] INFO: stage_01_data_ingestion: >>>>>>>>>> DATA INGESTION STAGE STARTED <<<<<<<<<<
[2024-10-07 16:03:22,403] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-07 16:03:22,407] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-07 16:03:22,409] INFO: common: created directory at: artifacts
[2024-10-07 16:03:22,409] INFO: common: created directory at: artifacts/data_ingestion
[2024-10-07 16:03:22,410] INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-07 16:04:07,746] INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view into file artifacts/data_ingestion/data.zip
[2024-10-07 16:04:08,918] INFO: stage_01_data_ingestion: >>>>>>>>>> DATA INGESTION STAGE COMPLETED <<<<<<<<<<

x=========================x
[2024-10-07 16:05:01,263] INFO: stage_02_prepare_base_model: ************************************************
[2024-10-07 16:05:01,264] INFO: stage_02_prepare_base_model: >>>>>>>>>> PREPARE BASE MODEL STARTED <<<<<<<<<<
[2024-10-07 16:05:01,267] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-07 16:05:01,271] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-07 16:05:01,273] INFO: common: created directory at: artifacts
[2024-10-07 16:05:01,274] INFO: common: created directory at: artifacts/prepare_base_model
[2024-10-07 16:05:01,896] WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2024-10-07 16:05:02,206] INFO: stage_02_prepare_base_model: >>>>>>>>>> PREPARE BASE MODEL COMPLETED <<<<<<<<<<

x=========================x
[2024-10-07 16:05:11,119] INFO: stage_03_model_training: ************************************************
[2024-10-07 16:05:11,119] INFO: stage_03_model_training: >>>>>>>>>> TRAINING STARTED <<<<<<<<<<
[2024-10-07 16:05:11,122] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-07 16:05:11,124] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-07 16:05:11,125] INFO: common: created directory at: artifacts
[2024-10-07 16:05:11,125] INFO: common: created directory at: artifacts\training
[2024-10-07 16:05:56,151] INFO: stage_03_model_training: >>>>>>>>>> TRAINING COMPLETED <<<<<<<<<<

x=========================x
[2024-10-07 16:06:07,653] INFO: stage_04_model_evaluation: ************************************************
[2024-10-07 16:06:07,653] INFO: stage_04_model_evaluation: >>>>>>>>>> EVALUATION STARTED <<<<<<<<<<
[2024-10-07 16:06:07,657] INFO: common: yaml file: config\config.yaml loaded successfully
[2024-10-07 16:06:07,661] INFO: common: yaml file: params.yaml loaded successfully
[2024-10-07 16:06:07,661] INFO: common: created directory at: artifacts
[2024-10-07 16:06:22,265] INFO: common: json file saved at: scores.json
[2024-10-07 16:06:22,267] INFO: common: json file saved at: scores.json
[2024-10-07 16:06:22,269] INFO: stage_04_model_evaluation: >>>>>>>>>> EVALUATION COMPLETED <<<<<<<<<<

x=========================x
[2024-10-07 16:15:44,916] INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.168.34.156:8080
[2024-10-07 16:15:44,917] INFO: _internal: [33mPress CTRL+C to quit[0m
[2024-10-07 16:15:56,235] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:15:56] "GET / HTTP/1.1" 200 -
[2024-10-07 16:16:45,288] ERROR: app: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 41, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-10-07 16:16:45,301] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:16:45] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2024-10-07 16:17:18,768] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:17:18] "GET / HTTP/1.1" 200 -
[2024-10-07 16:17:36,242] ERROR: app: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 41, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-10-07 16:17:36,248] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:17:36] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2024-10-07 16:19:55,736] INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.168.34.156:8080
[2024-10-07 16:19:55,736] INFO: _internal: [33mPress CTRL+C to quit[0m
[2024-10-07 16:19:59,436] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:19:59] "GET / HTTP/1.1" 200 -
[2024-10-07 16:20:06,102] ERROR: app: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 41, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\kabee\onedrive\desktop\ds proj3\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 15, in predict
    model = load_model(os.path.join("training", "model.h5"))
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kabee\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at training\model.h5
[2024-10-07 16:20:06,114] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:20:06] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2024-10-07 16:21:26,448] INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.168.34.156:8080
[2024-10-07 16:21:26,449] INFO: _internal: [33mPress CTRL+C to quit[0m
[2024-10-07 16:21:32,923] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:21:32] "GET / HTTP/1.1" 200 -
[2024-10-07 16:21:37,781] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:21:37] "POST /predict HTTP/1.1" 200 -
[2024-10-07 16:22:00,762] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:22:00] "POST /predict HTTP/1.1" 200 -
[2024-10-07 16:25:03,326] INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.168.34.156:8080
[2024-10-07 16:25:03,326] INFO: _internal: [33mPress CTRL+C to quit[0m
[2024-10-07 16:25:04,877] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:25:04] "GET / HTTP/1.1" 200 -
[2024-10-07 16:37:28,018] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:37:28] "POST /predict HTTP/1.1" 200 -
[2024-10-07 16:37:35,481] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:37:35] "POST /predict HTTP/1.1" 200 -
[2024-10-07 16:42:07,169] INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.168.34.156:8080
[2024-10-07 16:42:07,170] INFO: _internal: [33mPress CTRL+C to quit[0m
[2024-10-07 16:42:07,257] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:42:07] "GET / HTTP/1.1" 200 -
[2024-10-07 16:42:08,514] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:42:08] "GET / HTTP/1.1" 200 -
[2024-10-07 16:42:14,259] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:42:14] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -
[2024-10-07 16:42:17,545] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:42:17] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -
[2024-10-07 16:42:22,057] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:42:22] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -
[2024-10-07 16:42:23,282] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:42:23] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -
[2024-10-07 16:43:05,078] INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.168.34.156:8080
[2024-10-07 16:43:05,079] INFO: _internal: [33mPress CTRL+C to quit[0m
[2024-10-07 16:43:05,214] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:43:05] "GET / HTTP/1.1" 200 -
[2024-10-07 16:43:10,677] INFO: _internal: 127.0.0.1 - - [07/Oct/2024 16:43:10] "POST /predict HTTP/1.1" 200 -
